import { ResidentialComplex } from "../residentialComplex/residential-complex";
import { User } from "../user/user";
import { PropertyImage } from "./property-image";

export interface Property {
  id: string;
  type: string;
  propertyType: string;
  roomNumber: string;
  price: number;
  typeOfBuilding: string;
  yearOfBuilding: number;
  totalArea: number;
  areaLiving: number;
  areaKitchen: number;
  addressStreet: string;
  addressNumber: string;
  condition: string;
  telephone: string;
  internet: string;
  bathroom: string;
  heightOfCeiling: number;
  security: string;
  different: string;
  userId: string;
  user: User;
  images: PropertyImage[];
  userTelephone: string;
  userEmail: string;
  floorNumber: number;
  areaLand: number;
  sewageSystem: string;
  drinkingWater: string;
  electricity: string;
  heating: string;
  gas: string;
  roofCovering: string;
  propertyFloor: number;
  totalFloor: number;
  formerDormitory: boolean;
  balcony: string;
  balconyGlazed: boolean;
  door: string;
  parking: string;
  propertyFurnished: string;
  floor: string;
  residentialComplexId: string;
  residentialComplex: ResidentialComplex;
}
